### ISSUE TITLE
Publish new version into Rubygems

### ISSUE THREAD

**Issue by crbelaus** [crbelaus/jekyll-tailwind#11]
With pull request #10 merged it is a good time to release a new version of the gem.

Given that the internals have been rewritten I am leaning towards tagging it as 2.0.0. An argument can be made in favour of using 1.1.0 given that existing installations would still work without requiring changes in user code.

What do you think @skatkov?

**Comment by skatkov** [comment]
Hey!

Thanks for raising this issue.

I literally hacked this PR in 4 hours and don't feel confident, that it's good enough code to be called a stable release.


There are some things that would be nice to resolve before:
- maybe at least some test suite to cover these changes.
- deprecate 'config_path' in favor of 'config' to fully align with parameters that tailwindcss accepts.
- there is also a way to pass a debug flag to tailwindcss executable. Would be great to figure out how to map that with Jekyll.
- Now there are a lot of steps required to integrate this gem with Jekyll. Should we maybe build our own init script to automate that?
- it's now impossible to pass 'version' parameter. Should we give out a warning about that?

Would love to hear your thoughts.

**Comment by skatkov** [comment]
I double checked, but `--debug` attribute is not available. so no need to implement that.

**Comment by skatkov** [comment]
Did another PR to polish things up

https://github.com/crbelaus/jekyll-tailwind/pull/12

**Comment by skatkov** [comment]
After this PR is merged, I think we're good to publish a 2.0 version. But I'll keep this final decision up to you!

**Comment by crbelaus** [comment]
Version 2.0 is up and ready, so let's close this issue!
